SET SERVEROUTPUT ON;


CREATE OR REPLACE TRIGGER TRIGGER1
BEFORE UPDATE
OF rating 
ON APPSSERVER
FOR EACH ROW
DECLARE
A APPSSERVER.appId%TYPE;
B APPSSERVER.appName%TYPE;
C APPSSERVER.rating%TYPE;
BEGIN
  A :=:OLD.appId;
  B :=:OLD.appName;
  C :=:OLD.rating;
  insert into RatingUpdateTrackSite@site1 values(A,B,C);
  DBMS_OUTPUT.PUT_LINE('DATA UPDATED IN THE SITE');
END;
/

CREATE OR REPLACE TRIGGER DELETETRIGGER
AFTER DELETE
ON APPSSERVER
DECLARE
BEGIN

  
  DBMS_OUTPUT.PUT_LINE('1 ROW DELETED');
END;
/
CREATE OR REPLACE TRIGGER INSERTTRIGGER
AFTER INSERT
ON APPSSERVER
DECLARE
BEGIN
DBMS_OUTPUT.PUT_LINE('1 ROW INSERTED');
END;
/
CREATE OR REPLACE TRIGGER UPDATETRIGGER
AFTER UPDATE
ON APPSSERVER
DECLARE
BEGIN
DBMS_OUTPUT.PUT_LINE('1 ROW UPDATED');
END;
/
commit;

