SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE PACKAGE APPDATABASEMANAGESERVER AS
	PROCEDURE INSERTAPPINDATABASE(A IN APPSSERVER.appId%TYPE,B IN APPSSERVER.appName%TYPE,C IN APPSSERVER.appCategory%TYPE,D IN APPSSERVER.appSize_MB%TYPE,
	E IN APPSSERVER.totalDownloads_M%TYPE,F IN APPSSERVER.freeOrPremium%TYPE,G IN APPSSERVER.purchasePrice%TYPE,H IN APPSSERVER.rating%TYPE);
	
	PROCEDURE deleteAppFromDatabase(A IN APPSSERVER.appName%TYPE);
	PROCEDURE updateAppNameFromDatabase(A IN APPSSERVER.appName%TYPE,B IN APPSSERVER.appName%TYPE);
	
END APPDATABASEMANAGESERVER;
/




CREATE OR REPLACE PACKAGE BODY APPDATABASEMANAGESERVER AS


    --INSERT APP IN DATABASE
    PROCEDURE INSERTAPPINDATABASE(A IN APPSSERVER.appId%TYPE,B IN APPSSERVER.appName%TYPE,C IN APPSSERVER.appCategory%TYPE,D IN APPSSERVER.appSize_MB%TYPE,
	  E IN APPSSERVER.totalDownloads_M%TYPE,F IN APPSSERVER.freeOrPremium%TYPE,G IN APPSSERVER.purchasePrice%TYPE,H IN APPSSERVER.rating%TYPE)
    IS
    flag Integer :=0;
    flag1 Integer :=0;
	flag2 Integer :=0;
    flag3 Integer :=0;
    totalRow NUMBER;
    tempId APPSSERVER.appId%TYPE;
    BEGIN
     for i in (SELECT * FROM CategoryServer) LOOP
	    IF i.categoryName= C THEN
		   flag :=1;
		   EXIT;
		
		END IF;
	     
	  
	  END LOOP;
	  
	For j in (SELECT * FROM CategorySite@site1) LOOP
	    IF j.categoryName= C THEN
		   flag1 :=1;
		   EXIT;
		
		END IF;
	     
	  
	END LOOP;
	  
	For k in (SELECT * FROM APPSSERVER) LOOP
	    IF k.appName= B THEN
		   flag2 :=1;
		   EXIT;
		
		END IF;
	     
	  
	END LOOP;
	  
    For l in (SELECT * FROM APPSSITE@site1) LOOP
	    IF l.appName= B THEN
		   flag3 :=1;
		   EXIT;
		
		END IF;
	     
	  
	END LOOP;
	
	
	IF flag=1 or flag1=1 THEN
	   IF flag2=0 and flag3=0 THEN
	     SELECT COUNT(appId) into totalRow from APPSSITE@site1;
	     tempId :=41+totalRow;
	     INSERT INTO APPSSITE@site1 VALUES (tempId,B,C,D,E,F,G,H);
		 DBMS_OUTPUT.PUT_LINE('APP INSERTED IN THE SITE');
	   ELSE
	      DBMS_OUTPUT.PUT_LINE('APP ALREADY FOUND IN THE DATABASE');
		  
	   
	   END IF;
	
	
	ELSE
	   DBMS_OUTPUT.PUT_LINE('CATEGORY NOT LISTED IN THE DATABASE');
    
    END IF;

    END INSERTAPPINDATABASE;
	
	
	--DELETING APP FROM DATABASE
	PROCEDURE deleteAppFromDatabase(A IN APPSSERVER.appName%TYPE)
	IS
	flag Integer :=0;
    flag1 Integer :=0;
	BEGIN
    for i in (SELECT * FROM APPSSERVER) LOOP
	    IF i.appName= A THEN
		   flag :=1;
		   EXIT;
		
		END IF;
	     
	  
	  END LOOP;
	  
	For j in (SELECT * FROM APPSSITE@site1) LOOP
	    IF j.appName= A THEN
		   flag1 :=1;
		   EXIT;
		
		END IF;
	     
	END LOOP;
	
	If flag =0 and flag1=0 THEN
	      DBMS_OUTPUT.PUT_LINE('APP NOT FOUND IN THE DATABASE');
	ELSIF (flag =1 and flag1=0) THEN
	     DELETE FROM APPSSERVER WHERE appName=A;
	ELSIF (flag1 =1 and flag=0)  THEN
	     DELETE FROM APPSSITE@site1 WHERE appName=A;
	END IF;
	
	
	END deleteAppFromDatabase;

    
	--UPDATING APPNAME IN THE DATABASE
	PROCEDURE updateAppNameFromDatabase(A IN APPSSERVER.appName%TYPE,B IN APPSSERVER.appName%TYPE)
	IS
	flag Integer :=0;
    flag1 Integer :=0;
	tempId APPSSERVER.appId%TYPE;
	BEGIN
	for i in (SELECT * FROM APPSSERVER) LOOP
	    IF i.appName= A THEN
		   flag :=1;
		   EXIT;
		
		END IF;
	     
	  
	  END LOOP;
	  
	For j in (SELECT * FROM APPSSITE@site1) LOOP
	    IF j.appName= A THEN
		   flag1 :=1;
		   EXIT;
		
		END IF;
	     
	END LOOP;
	
	If flag =0 and flag1=0 THEN
	      DBMS_OUTPUT.PUT_LINE('APP NOT FOUND IN THE DATABASE');
	ELSIF (flag =1 and flag1=0) THEN
	    SELECT appId into tempId FROM APPSSERVER WHERE appName=A;
	    UPDATE APPSSERVER SET appName=B WHERE appId=tempId;
	ELSIF (flag1 =1 and flag=0)  THEN
	    SELECT appId into tempId FROM APPSSITE@site1 WHERE appName=A;
	    UPDATE APPSSITE@site1 SET appName=B WHERE appId=tempId;
	END IF;
	
	
	
	END updateAppNameFromDatabase;
	
	
	

END APPDATABASEMANAGESERVER;
/



ACCEPT X NUMBER PROMPT "ENTER 1 FOR INSERTING APP,2 FOR DELETING,3 FOR UPDATINGNAME:"
ACCEPT A NUMBER PROMPT "ENTER APPID:";
ACCEPT B CHAR PROMPT "ENTER APPNAME:"
ACCEPT C CHAR PROMPT "ENTER APPCATEGORY:"
ACCEPT D NUMBER PROMPT "ENTER APPSIZE:"
ACCEPT E NUMBER PROMPT "ENTER TOTALDOWNLOADS:"
ACCEPT F NUMBER PROMPT "ENTER FREEORPREMIUM:"
ACCEPT G NUMBER PROMPT "ENTER PURCHASEPRICE:"
ACCEPT H NUMBER PROMPT "ENTER RATING:"

ACCEPT I CHAR PROMPT "ENTER UPDATEDNAME:"

DECLARE
CHOICE NUMBER:=&X;
APPID APPSSERVER.appId%TYPE:=&A;
APPNAME APPSSERVER.appName%TYPE:='&B';
APPCATEGORY APPSSERVER.appCategory%TYPE:='&C';
APPSIZE APPSSERVER.appSize_MB%TYPE:=&D;
TOTALDOWNLOADS APPSSERVER.totalDownloads_M%TYPE:=&E;
FREEORPREMIUM APPSSERVER.freeOrPremium%TYPE:=&F;
PURCHASEPRICE APPSSERVER.purchasePrice%TYPE:=&G;
RATING APPSSERVER.rating%TYPE:=&H;
UPDATEDNAME APPSSERVER.appName%TYPE:='&I';
ERROR EXCEPTION;
BEGIN
  IF CHOICE<1 OR CHOICE>3 THEN
     RAISE ERROR;
  END IF;
  
  IF CHOICE=1 THEN
     APPDATABASEMANAGESERVER.INSERTAPPINDATABASE(APPID,APPNAME,APPCATEGORY,APPSIZE,TOTALDOWNLOADS,FREEORPREMIUM,PURCHASEPRICE,RATING);
  ELSIF CHOICE=2 THEN
      APPDATABASEMANAGESERVER.deleteAppFromDatabase(APPNAME); 
  ELSIF CHOICE=3 THEN
      APPDATABASEMANAGESERVER.updateAppNameFromDatabase(APPNAME,UPDATEDNAME); 
  END IF;
  
  
EXCEPTION
   WHEN ERROR THEN
      DBMS_OUTPUT.PUT_LINE('YOY CHOOSE THE WRONG OPTION');


END;
/

commit;

